# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'a:\Main\CODE\GUI\GradeVision-QT-material - TESTVERSION\gallary\app\view\grading2.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(814, 632)
        self.gridLayout_2 = QtWidgets.QGridLayout(Form)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.SimpleCardWidget_2 = SimpleCardWidget(Form)
        self.SimpleCardWidget_2.setObjectName("SimpleCardWidget_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.SimpleCardWidget_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.PlainTextEdit = PlainTextEdit(self.SimpleCardWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PlainTextEdit.sizePolicy().hasHeightForWidth())
        self.PlainTextEdit.setSizePolicy(sizePolicy)
        self.PlainTextEdit.setMinimumSize(QtCore.QSize(563, 0))
        self.PlainTextEdit.setObjectName("PlainTextEdit")
        self.gridLayout_3.addWidget(self.PlainTextEdit, 1, 0, 1, 1)
        self.StrongBodyLabel = StrongBodyLabel(self.SimpleCardWidget_2)
        self.StrongBodyLabel.setObjectName("StrongBodyLabel")
        self.gridLayout_3.addWidget(self.StrongBodyLabel, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.SimpleCardWidget_2, 1, 0, 1, 1)
        self.SimpleCardWidget = SimpleCardWidget(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SimpleCardWidget.sizePolicy().hasHeightForWidth())
        self.SimpleCardWidget.setSizePolicy(sizePolicy)
        self.SimpleCardWidget.setMinimumSize(QtCore.QSize(200, 236))
        self.SimpleCardWidget.setObjectName("SimpleCardWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.SimpleCardWidget)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 1, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 1, 2, 1, 1)
        self.CaptionLabel = CaptionLabel(self.SimpleCardWidget)
        self.CaptionLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.CaptionLabel.setObjectName("CaptionLabel")
        self.gridLayout.addWidget(self.CaptionLabel, 2, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem2, 0, 1, 1, 1)
        self.ProgressRing = ProgressRing(self.SimpleCardWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ProgressRing.sizePolicy().hasHeightForWidth())
        self.ProgressRing.setSizePolicy(sizePolicy)
        self.ProgressRing.setMinimumSize(QtCore.QSize(100, 100))
        self.ProgressRing.setTextVisible(True)
        self.ProgressRing.setObjectName("ProgressRing")
        self.gridLayout.addWidget(self.ProgressRing, 1, 1, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem3, 3, 1, 1, 1)
        self.gridLayout_2.addWidget(self.SimpleCardWidget, 1, 1, 1, 1)
        self.SimpleCardWidget_3 = SimpleCardWidget(Form)
        self.SimpleCardWidget_3.setObjectName("SimpleCardWidget_3")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.SimpleCardWidget_3)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.TitleLabel = TitleLabel(self.SimpleCardWidget_3)
        self.TitleLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.TitleLabel.setObjectName("TitleLabel")
        self.gridLayout_4.addWidget(self.TitleLabel, 0, 0, 1, 1)
        self.images_label = QtWidgets.QLabel(self.SimpleCardWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.images_label.sizePolicy().hasHeightForWidth())
        self.images_label.setSizePolicy(sizePolicy)
        self.images_label.setText("")
        self.images_label.setObjectName("images_label")
        self.gridLayout_4.addWidget(self.images_label, 1, 0, 1, 1)
        self.gridLayout_2.addWidget(self.SimpleCardWidget_3, 0, 0, 1, 2)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.StrongBodyLabel.setText(_translate("Form", "Current Events:"))
        self.CaptionLabel.setText(_translate("Form", "Caption label"))
        self.TitleLabel.setText(_translate("Form", "Grading:"))
from qfluentwidgets import CaptionLabel, PlainTextEdit, ProgressRing, SimpleCardWidget, StrongBodyLabel, TitleLabel
